USE [master]
GO
/****** Object:  Database [EmploymentSystem]    Script Date: 11/9/2024 8:42:39 AM ******/
CREATE DATABASE [EmploymentSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmploymentSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmploymentSystem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmploymentSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\EmploymentSystem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [EmploymentSystem] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmploymentSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EmploymentSystem] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EmploymentSystem] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EmploymentSystem] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EmploymentSystem] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EmploymentSystem] SET ARITHABORT OFF 
GO
ALTER DATABASE [EmploymentSystem] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EmploymentSystem] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EmploymentSystem] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EmploymentSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EmploymentSystem] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EmploymentSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EmploymentSystem] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EmploymentSystem] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EmploymentSystem] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EmploymentSystem] SET  DISABLE_BROKER 
GO
ALTER DATABASE [EmploymentSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EmploymentSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EmploymentSystem] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EmploymentSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EmploymentSystem] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EmploymentSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EmploymentSystem] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EmploymentSystem] SET RECOVERY FULL 
GO
ALTER DATABASE [EmploymentSystem] SET  MULTI_USER 
GO
ALTER DATABASE [EmploymentSystem] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EmploymentSystem] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EmploymentSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EmploymentSystem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EmploymentSystem] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EmploymentSystem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EmploymentSystem', N'ON'
GO
ALTER DATABASE [EmploymentSystem] SET QUERY_STORE = ON
GO
ALTER DATABASE [EmploymentSystem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [EmploymentSystem]
GO
/****** Object:  Table [dbo].[UserType]    Script Date: 11/9/2024 8:42:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_UserType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Vacancy]    Script Date: 11/9/2024 8:42:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Vacancy](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[MaxNumberOfApplications] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ExpiryDate] [datetime] NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_Vacancy] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[VacancyApplications]    Script Date: 11/9/2024 8:42:40 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VacancyApplications](
	[ApplicantId] [int] NOT NULL,
	[VacancyId] [int] NOT NULL,
	[ApplicationDate] [date] NOT NULL,
 CONSTRAINT [PK_VacancyApplications] PRIMARY KEY CLUSTERED 
(
	[ApplicantId] ASC,
	[VacancyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [EmploymentSystem] SET  READ_WRITE 
GO
